using BankingApi.Application.Common.Exceptions;
using BankingApi.Domain.Entities;
using BankingApi.Domain.Enums;
using BankingApi.Infrastructure.Persistence;
using BankingApi.Infrastructure.Services;
using Microsoft.EntityFrameworkCore;
using BC = BCrypt.Net.BCrypt;

namespace BankingApi.Application.Auth.Commands;

/// <summary>
/// Handles RegisterUserCommand.
/// Creates a User + Customer Account atomically.
/// Account number is generated by reading MAX(AccountNumber) — never
/// hardcoded — so NGL accounts (0000000001, 0000000002, 0000000003) are always
/// skipped correctly.
/// </summary>
public class RegisterUserHandler
{
    private readonly BankingDbContext _db;
    private readonly IAccountNumberGenerator _accountNumberGenerator;

    public RegisterUserHandler(
        BankingDbContext db,
        IAccountNumberGenerator accountNumberGenerator)
    {
        _db = db;
        _accountNumberGenerator = accountNumberGenerator;
    }

    public async Task<RegisterUserResult> Handle(
        RegisterUserCommand cmd,
        CancellationToken ct)
    {
        // ── Guard: duplicate email (belt-and-suspenders; validator also checks) ──
        var emailExists = await _db.Users
            .AnyAsync(u => u.Email == cmd.Email, ct);

        if (emailExists)
            throw new ValidationException(
                new Dictionary<string, string[]>
                {
                    ["email"] = new[] { "An account with this email address already exists." }
                });

        // ── Guard: duplicate BVN ───────────────────────────────────────────────
        var bvnExists = await _db.Accounts
            .AnyAsync(a => a.BVN == cmd.BVN, ct);

        if (bvnExists)
            throw new ValidationException(
                new Dictionary<string, string[]>
                {
                    ["bvn"] = new[] { "An account with this BVN already exists." }
                });

        var now = DateTime.UtcNow;
        var user = new User
        {
            Id = Guid.NewGuid(),
            FirstName = cmd.FirstName.Trim(),
            MiddleName = cmd.MiddleName?.Trim(),
            LastName = cmd.LastName.Trim(),
            Gender = cmd.Gender,
            Address = cmd.Address?.Trim(),
            State = cmd.State?.Trim(),
            Country = cmd.Country.Trim(),
            Email = cmd.Email.Trim().ToLowerInvariant(),
            Password = BC.HashPassword(cmd.Password, workFactor: 12),
            CreatedAt = now
        };

        // Generate next account number across ALL accounts (Customer + NGL)
        var accountNumber = await _accountNumberGenerator.GenerateAsync(ct);

        var account = new Account
        {
            Id = Guid.NewGuid(),
            UserId = user.Id,
            AccountNumber = accountNumber,
            BVN = cmd.BVN.Trim(),
            Balance = 0.00m,
            Currency = "NGN",
            AccountType = AccountType.Customer,
            NglPoolType = null,
            IsSystemAccount = false,
            CreatedAt = now,
            UpdatedAt = now
        };

        _db.Users.Add(user);
        _db.Accounts.Add(account);
        await _db.SaveChangesAsync(ct);

        return new RegisterUserResult(
            UserId: user.Id,
            FullName: user.FullName,
            Email: user.Email,
            AccountNumber: account.AccountNumber,
            Currency: account.Currency,
            AccountType: account.AccountType,
            CreatedAt: user.CreatedAt);
    }
}